In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
lamost = pd.read_csv('full_data.csv')
lamost.head(3)

,Unnamed: 0,obsid,uid,gp_id,designation,obsdate,lmjd,mjd,planid,spid,...,logg_err,source_id,solution_id,ra,dec,flux,flux_error,SNR_gaia,mean_snr_lamost,SNR_lamost_mean
0,14,4302066,G16614776306411,3421375900092772352,J052000.45+271629.1,2011-11-12,55878,55877,GAC_080N28_B1,2,...,-9999.0,3421375900092772352,4545469030156206081,80.001905,27.274760,"[4.702319e-17,3.3818403e-17,2.890806e-17,3.197...","[5.6705386e-18,4.096698e-18,3.301896e-18,2.841...",51.742792,2.790,2.790
1,16,4303076,G16616211403281,3422425109064461184,J051729.38+284840.9,2011-11-12,55878,55877,GAC_080N28_B1,3,...,-9999.0,3422425109064461184,4545469030156206081,79.372464,28.811368,"[3.01145e-17,1.9405108e-17,2.3832594e-17,2.871...","[3.5389086e-18,2.5089825e-18,1.987536e-18,1.92...",54.041758,11.546,11.546
2,27,4516120,G16860278183090,507587382602316544,J020728.65+601542.4,2011-11-13,55879,55878,B7905_1,16,...,-9999.0,507587382602316544,4545469030156206081,31.869457,60.261809,"[9.702513e-18,1.07273455e-17,1.2335912e-17,1.1...","[3.0450003e-18,2.2279167e-18,1.8311533e-18,1.5...",54.893125,10.868,10.868

In [6]:
gaia = pd.read_csv('flux_gaia.csv')
gaia.pop('Unnamed: 0')
gaia.head(3)

,336.0,338.0,340.0,342.0,344.0,346.0,348.0,350.0,352.0,354.0,...,1002.0,1004.0,1006.0,1008.0,1010.0,1012.0,1014.0,1016.0,1018.0,1020.0
0,3.360000e+02,3.380000e+02,3.400000e+02,3.420000e+02,3.440000e+02,3.460000e+02,3.480000e+02,3.500000e+02,3.520000e+02,3.540000e+02,...,1.002000e+03,1.004000e+03,1.006000e+03,1.008000e+03,1.010000e+03,1.012000e+03,1.014000e+03,1.016000e+03,1.018000e+03,1.020000e+03
1,4.702319e-17,3.381840e-17,2.890806e-17,3.197863e-17,3.564173e-17,3.332230e-17,2.806158e-17,2.743496e-17,3.304186e-17,3.672462e-17,...,5.069003e-17,4.959312e-17,4.898656e-17,4.743713e-17,4.650921e-17,4.596943e-17,4.492957e-17,4.557578e-17,4.534698e-17,4.696055e-17
2,3.011450e-17,1.940511e-17,2.383259e-17,2.871886e-17,2.614950e-17,2.139932e-17,2.265599e-17,2.731747e-17,2.684658e-17,2.148471e-17,...,3.062854e-17,2.967638e-17,2.922163e-17,2.847382e-17,2.842568e-17,2.898779e-17,2.959787e-17,3.165253e-17,3.332371e-17,3.641728e-17

In [7]:
gaia = gaia.drop([0])
gaia = gaia*1e+19

In [8]:
param = pd.read_csv('paramfull')
#param.pop('Unnamed: 0')
param.head(3)

,source_id,parallax,phot_g_mean_mag,bp_rp,radial_velocity,radial_velocity_error,logg_gspphot,teff_gspphot,mh_gspphot
0,3421375900092772352,0.807234,13.880873,0.986093,NaN,NaN,4.0996,9442.535,-0.7773
1,3422425109064461184,0.591876,14.216793,0.849067,NaN,NaN,4.1700,7989.195,-0.5155
2,507587382602316544,0.670442,14.406285,1.488364,5.927681,5.506062,3.5397,8880.671,-0.1447

In [13]:
len(lamost[lamost.teff == -9999])

563